import "es6-promise/auto";
import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import "../public/assets/css/style.css";
import store from "./store";
const app = createApp(App);
app.use(router);
app.use(store);
app.mount("#app");
